name: fireworks
description: A new Flutter project.
author: Emily Fortuna <efortuna@google.com>
homepage: https://github.com/efortuna/fireworks

version: 0.9.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true